CreateClientConVar( "proximity_voice_enabled", "0", true, true )
cvars.AddChangeCallback( "proximity_voice_enabled", function( name, old, new )
	net.Start( "proximity_voice_enabled_changed" )
		net.WriteBool( tobool(new) )
	net.SendToServer()
end)
